#!/usr/bin/env bash
# The script should display list of currently running processes
# It must show all processes for all users, even those who might not have a TTY
# It should display a user-oriented format
# Show process hierarchy
ps -a -x -u -f
