#!/usr/bin/env bash
#Bash script that
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
clean_up='rm /var/run/myscript.pid; exit $?'
echo $$ > "/var/run/myscript.pid"

