#!/usr/bin/env bash
# A script extends previous exercise command and shows line containing bash word, that allowes you to get the PID of your Bash process
# You cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
